import { Merriweather,Poppins } from "next/font/google";
import "./globals.css";

const merriweather = Merriweather({ 
  variable:"--font-merriweather",
  subsets: ["latin"],
  weight:["300","400","700","900"],
  display:"swap",
});
const poppins = Poppins({ 
  variable:"--font-poppins",
  subsets: ["latin"],
  weight:["400","500","600","700","900"],
  display:"swap",
});

export const metadata = {
  title: "Travel BD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${merriweather.variable} ${poppins.variable}`}>{children}</body>
    </html>
  );
}
